import { useState } from "react";
import { useNavigate } from 'react-router-dom';
import { resetPassword } from "../services/Authentication.service";

function ResetPasswordAction(props) { 

  var [password, setPassword] = useState('');
  var [inputType, setInputType] = useState('password');

  var [confirmPassword, setConfirmPassword] = useState('');
  var [inputTypeConfirmPassword, setInputTypeConfirmPassword] = useState('password')

  const navigate = useNavigate();

  //////////////////////////////////// handle the fields  ////////////////////////////////////
//   function handleEmail(e) {
//     e.preventDefault();
//     setEmailAddress(e.target.value);
//   }

  // handle password
  function handlePassword(e) {
    e.preventDefault();
    setPassword(e.target.value);
  }

  // handle confirmation password
  function handleConfirmPassword(e) {
    e.preventDefault();
    setConfirmPassword(e.target.value)
  }

  //////////////////////////////////// handle the "show/hide" password and confirm password ////////////////////////////////////
  
  // handle password
  function togglePasswordVisibility(e) {
    e.preventDefault();
    setInputType(inputType === 'password' ? 'text' : 'password');
  }

  // handle confirmation password
  function toggleConfirmPasswordVisibility(e) {
    e.preventDefault();
    setInputTypeConfirmPassword(inputTypeConfirmPassword === 'password' ? 'text' : 'password');
  }

  ///////////////////////////////////// Handles the retrive of the parameters ////////////////////////////////////
  function getUrlParams() {
    const params = new URLSearchParams(window.location.search);
    return {
      accessToken: params.get('access-token'),
      uid: params.get('uid'),
      client: params.get('client'),
      token: params.get('token')
    };
  }

///////////////////////////////////// Handles the password reset ////////////////////////////////////
// on this process, we will need:  
// access-token, client, token, uid (email adddress)
// Those are generated by a link sent via email using the handleForgetPassword
async function handleResetPassword(e) {
    e.preventDefault();

    const { accessToken, uid, client, token } = getUrlParams();
  
    try {

      const response = await resetPassword(password, confirmPassword, accessToken, uid, client, token);     
      
      alert(response)   
      
      navigate('/login?password_reset_success=true'); 

  
    } catch (error) {
      if (error.response) {
        console.error("Error on the request:", error.response.data);
      } else {
        console.error("Unknown Erro:", error.message);
      }  
      alert('Erro ao resetar o password.');
    }
  }  

  
  return (
    <div className="">

        <label for="password">Password</label><br></br>
        <input type={inputType} id="password" name="password" value={password} onChange={handlePassword} /> 
        <button onClick={togglePasswordVisibility}>
        {inputType === 'password' ? 'Mostrar Senha' : 'Esconder Senha'}
        </button><br />

        <label for="confirmPassword">Confirm Password</label><br></br>
        <input type={inputTypeConfirmPassword} id="confirmPassword" name="confirmPassword" value={confirmPassword} onChange={handleConfirmPassword} /> 
        <button onClick={toggleConfirmPasswordVisibility}>
        {inputTypeConfirmPassword === 'password' ? 'Mostrar Senha' : 'Esconder Senha'}
        </button><br /><br />

        <button onClick={handleResetPassword}>Reset Password</button>
      
    </div>
  );
}

export default ResetPasswordAction;